variables:
  TEST_FILE: "./.githooks/pre-commit"

stages:
  - shell_test

shell_test:
  stage: shell_test
  tags:
    - bash
  script:
    - shfmt -d -i 4 $(find . -name "*.sh" -not -path "./.githooks/*")
